In [2]:
#importing important libraries that we will use in ore model
import numpy as np
import pandas as pd 
import sklearn
colum_names = ["crim","ZN","INDUS","CHAS","NOX","RM","AGE","DIS","RAD","TAX","B"]
bos1 = pd.read_csv("housing.csv",delimiter = r"\s+",names = colum_names)
bos1.head(10)

,,,crim,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,B
0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [21]:
#checking is there any missing value 
bos1.isna().sum()

crim     0
ZN       0
INDUS    0
CHAS     0
NOX      0
RM       0
AGE      0
DIS      0
RAD      0
TAX      0
B        0
dtype: int64

In [8]:
#splitting the data 30% goes for testing and 70% for training 
from sklearn.model_selection import train_test_split
x = np.array(bos1.iloc[:,0:13])
y = np.array(bos1["B"])
x_train, x_test, y_train,y_test = train_test_split(x,y,test_size = 0.30 ,random_state = 5)

In [23]:
#importing KNN alg from sklearn and giving the value of nearest Neighbor = 5
from sklearn.linear_model import LinearRegression
from sklearn.neighbors import KNeighborsRegressor
lr = LinearRegression()
lr.fit(x_train,y_train)

Nn = KNeighborsRegressor(5)
Nn.fit(x_train,y_train)
pred_Nn = Nn.predict(x_test)

In [15]:
#checking which value would be best for nearest Neighbor
for i in range(1, 50):
    model = KNeighborsRegressor(i)
    model.fit(x_train, y_train)
    
    pred_y = model.predict(x_test)
    mse = sklearn.metrics.mean_squared_error(y_test, pred_y, squared=False)
    
    print("Error for k = {}: {}".format(mse,i))

Error for k = 4.429639999629292: 1
Error for k = 4.278151731395476: 2
Error for k = 4.47355125361423: 3
Error for k = 4.82246533165351: 4
Error for k = 5.060922528759481: 5
Error for k = 5.465144404548987: 6
Error for k = 5.7335717774878106: 7
Error for k = 5.948837513595231: 8
Error for k = 6.067918465414971: 9
Error for k = 6.315914787682237: 10
Error for k = 6.506281971231281: 11
Error for k = 6.677733173758313: 12
Error for k = 6.835575716446456: 13
Error for k = 6.886086559446449: 14
Error for k = 6.968808283263996: 15
Error for k = 7.05837297908251: 16
Error for k = 7.114748389492351: 17
Error for k = 7.2318287156465235: 18
Error for k = 7.308953316706823: 19
Error for k = 7.367289914940871: 20
Error for k = 7.480966419855722: 21
Error for k = 7.582049398818527: 22
Error for k = 7.632498506674119: 23
Error for k = 7.710971484302425: 24
Error for k = 7.737473135741137: 25
Error for k = 7.800425608651964: 26
Error for k = 7.871875323376209: 27
Error for k = 7.947720252795921: 28
Error for k = 8.031611674766696: 29
Error for k = 8.07951401450151: 30
Error for k = 8.11231961383121: 31
Error for k = 8.168827234312527: 32
Error for k = 8.23156147671171: 33
Error for k = 8.278786084613142: 34
Error for k = 8.301814329412755: 35
Error for k = 8.313813218560176: 36
Error for k = 8.335974412002628: 37
Error for k = 8.361483588671073: 38
Error for k = 8.380233033392845: 39
Error for k = 8.40434147773293: 40
Error for k = 8.44086635941245: 41
Error for k = 8.486963797281096: 42
Error for k = 8.508381163713908: 43
Error for k = 8.52157257329308: 44
Error for k = 8.5441594470299: 45
Error for k = 8.549352148161189: 46
Error for k = 8.55617737468464: 47
Error for k = 8.58137205665422: 48
Error for k = 8.597938232946277: 49

In [18]:
mse_Nn = sklearn.metrics.mean_squared_error(y_test, pred_Nn, squared=False)
print("Error for KNN algorithm = {}".format(mse_Nn))

Error for KNN algorithm = 4.47355125361423